[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "create_python_project"
version = "2025.0.0"
authors = [
    {name = "Le Ngoc Chau", email = "playerzawesome@gmail.com"},
]
description = "Use this project to create a starter template for your next Python project."
readme = "README.md"
dependencies = [
    "click==8.1.8",
    "jinja2==3.1.6",
]

[project.scripts]
create-python-project = "create_python_project.main:cli"

[tool.setuptools.packages.find]
where = ["src"]
include = ["create_python_project"]

[tool.setuptools.package-data]
"create_python_project.templates" = ["*"]

[tool.ruff]
line-length = 119

[tool.isort]
line_length = 119
